---
title: 'Adoption Barriers'
teaching: 10
exercises: 2
---


Despite the manu advances of computer graphics, and
the development of hadrware and toolkits for Virtual and Mixed Reality systems, 
multiple challenges have slowed down its adoption.

Let's explore this in more detail

::::::::::::::::::::::::::::::::::::: challenge

Which have been the challenges for the widespread consumer adoption of Virtual Reality technologies in the last 40 decades?
::::::::::::::::::::::::::::::::::::: 

## Informing our approach
Addressing challenges can inform the approach for building new VR  applications.

Think about how you might address some issues via software development.

The hardware will keep improving.

::::::::::::::::::::::::::::::::::::: keypoints 

- Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::

