---
title: 'Origins of Mixed Reality Systems'
teaching: 10
exercises: 2
---


## Computer Graphics and Mixed Reality
![](fig/AdobeStock_625890170.jpeg){alt="front banner education"}

Mixed Reality systems have a long history in Computer Science.

Applications for immersion and experiencing artificial worlds have
been envisaged for long time. 

> There has been a lot of talk asking "What is
VR?" I feel that the essence is the notion of
inclusion, of something that surrounds you, of
something that is an environment. There is kind
of a strange thing that happens when you take a
picture and expand it in your visual field to past
60 °. You get sucked in. It becomes a place. It
also keys off an emotional response. 
(William Bricken, 1990)


::::::::::::::::::::::::::::::::::::: challenge 

## Challenge: Early computer graphics systems


This publication is a record from a panel
at the SIGGRAPH conference in 1990. In it
it describes the type of graphic systems which are
"artificial realities" generated by computers 
which surround the
user. They specify that is mostly computer graphics
professionals and researchers who have access to these systems.

Explore further the following questions:

- How they defined Virtual Reality systems?
- What were the applications they envisaged the systems could be used for?
- What were their predictions for this type of technology?

John Barlow, Esther Dyson, Timothy Leary, William Bricken, Warren Robinett, Jaron Lanier, and Bob Jacobson. 1990. Hip, hype and hope—the three faces of virtual worlds (panel session). In ACM SIGGRAPH 90 Panel Proceedings (SIGGRAPH '90). Association for Computing Machinery, New York, NY, USA, 1001–1029. [https://doi.org/10.1145/328750.328798](https://doi.org/10.1145/328750.328798)


:::::::::::::::::::::::::::::::::


## Fast forward since 1990s

[![History VR](https://i.ytimg.com/vi/43mA_ypfwKg/hqdefault.jpg)](https://www.youtube.com/watch?v=43mA_ypfwKg "History of Virtual Reality - Reality Check &copy; GameSpot"){alt="video"}

[![History AR](https://i.ytimg.com/vi/_m44ynMTogY/hqdefault.jpg)](https://www.youtube.com/watch?v=_m44ynMTogY "History of Mixed Reality &copy; Affair Island"){alt="video"}


## More information

- Randy Pausch. (2007, September). Really achieving your childhood dreams [Video]. TED Conferences. URL: [https://www.ted.com/talks/randy_pausch_really_achieving_your_childhood_dreams]([https://www.ted.com/talks/randy_pausch_really_achieving_your_childhood_dreams])

- Warren Robinett. Warren Robinett's Home Page. Accessed October 2023. URL: [http://warrenrobinett.com/](http://warrenrobinett.com/)

::::::::::::::::::::::::::::::::::::: keypoints 

- Virtual Reality Systems have a long history since the early days of computer
graphic 
- Researchers envisaged a wide variety of applications, beyond games,
for these systems including tele-operation, communicate different types of 
information/phenomena (e.g. electronic, molecules) to match with our in-built sense,
building the virtual worlds from the inside.

::::::::::::::::::::::::::::::::::::::::::::::::

