---
title: 'VR History'
teaching: 10
exercises: 2
---

Mixed Reality systems, encompassing both Virtual Reality and Augmented Reality, have a rich and extensive history within the field of Computer Science. 

The applications of immersion and the experience of artificial worlds have been envisioned for a long time.

Let's start with a look at the early 1990's.

> There has been a lot of talk asking "What is
VR?" I feel that the essence is the notion of
inclusion, of **something that surrounds you**, of
something that is **an environment**. There is kind
of a strange thing that happens when you take a
picture and expand it in your visual field to past
60°. You get sucked in. It becomes a place. It
also keys off an emotional response. 
(William Bricken, 1990)

:::::::::::::::::::::::::::: challenge

### Challenge: Visual field exploration 

In groups of 2 do the following exercise:

1. Gather two small objects or markers.
2. Person#1 should keep both objects in front of Person#2's eyes.
3. Person#2 focus on one object and close one eye.
4. While Person#2 keeps their gaze fixed on one of the objects, Person#1 should 
move the second object slowly to the side of their open eye. At some point, Person#2 
should notice the object disappears.
5. Repeat the exercise with the other eye.

Reflect:

1. What did you notice about your peripheral vision?

2. How large do you think is your field of view (FOV).

:::::::::: solution

Humans have a slightly over 210-degree forward-facing horizontal arc of their visual field.

![Field of View](https://upload.wikimedia.org/wikipedia/commons/1/11/FOV_both_eyes.svg){alt="FOV" width='300px'}
::::::::::::::::::::::::::::
:::::::::::::::::::::::::::: 


**Virtual Reality**, **Virtual Environments**, **Artificial Realities**, and
other related terms have been used to describe
these technologies. Let's explore more the founders of these ideas.

::::::::::::::::::::::::::::::::::::: challenge 

## Let's look at definitions

- [What are the key elements of a Virtual Reality Systems?](https://PollEv.com/free_text_polls/QvVXqjPKVVtMQFaAQbCch/respond)

:::::::::::::::::::::::::::::::::

## Definitions
- What is a VR System?
- What is an Extended Reality (XR) System?
- Which techniques and technologies are relevant for these systems?


In 1987, [computer scientists developed](https://dl.acm.org/doi/10.1145/319120.319127) 
"head-mounted, wide-angle, stereoscopic display systems" that were controlled by the user's position. 
"The system provides a multisensory, interactive display environment in which a user can virtually explore a 360-degree synthesized or remotely sensed environment and can viscerally interact with its components."[^1][^2].

This definition frames Virtual Reality Systems as interfaces to interactive, computer-generated environments.
A Virtual Reality (VR) system immerses users in a fully simulated environment, 
often experienced through devices like headsets, gloves, and motion controllers.

Extended reality, on the other hand, introduces varying degrees of integration between the physical 
world and digital environments. These systems range from fully immersing users in a virtual space to 
enabling interaction with both the real and virtual worlds simultaneously.

Developing these systems involves techniques from software engineering, 
linked data, computer graphics, and system design, 
making these disciplines essential to building immersive environments.


## The Three Faces of Virtual Worlds

The panel at SIGGRAPH 1990 [^2] featuring prominent thinkers like John Barlow, Esther Dyson, Timothy Leary, William Bricken, Warren Robinett, and Jaron Lanier, with Bob Jacobson as the chair, 
explored the potential and challenges of virtual worlds in three key dimensions. 
Their discussion explore the cultural "hip" around  virtual worlds, which were surrounded by the "hype".
They explored how VR value lies in the "hope" that they offer for new ways of interaction, 
learning, and creative expression, but only if their limitations and realities are fully understood.

The panel also discusses a type of graphic systems which includes
*virtual reality* generated by computers 
which surround the user through additional hardware, such as gloves, clothing, 
and goggles. 




::::::::::::::::::::::::::::::::::::: challenge 

### Challenge: Explore the article in 5 minutes

Consider the following questions in relation to the article:

1. What was the resolution of the headsets available to the attendees?
2. What did the presenters envision people would need to wear to interact with graphical virtual worlds?
3. Which senses did the presenters believe were most important to engage?
4. What scenarios did they foresee for the application of this technology?
:::::::::::::::::::::::::::::::::

## Immersive Virtual Environments class, San Francisco Art Institute, 1990

In the spring of 1990 Michael Naimark taught a class entitled "Immersive Virtual Environments" 
at the San Francisco Art Institute. 
This was a moment in time when "virtual reality" began gaining visibility, particularly through the popular press. 
The students, both enthusiastic and critical, prepared this tape as their response.
**URL:** http://www.naimark.net/projects/virtuality.html


[![Immersive Virtual Environments class, San Francisco Art Institute, 1990](https://i.ytimg.com/vi/BsWFQ3-7D9c/hqdefault.jpg)](https://www.youtube.com/watch?v=BsWFQ3-7D9c Virtuality Incorporated" (excerpt), 1990 video, SF Art Institute &copy; Naimark et al."){alt="video" }



## Historical Evolution Of Virtual Reality

[![The Incredible Evolution Of Virtual Reality](https://i.ytimg.com/vi/yXP307L-fdM/hqdefault.jpg)](https://www.youtube.com/watch?v=yXP307L-fdM "The Incredible Evolution Of Virtual Reality &copy; TheGamer"){alt="video" }


### Additional Links
- Randy Pausch. (2007, September). Really achieving your childhood dreams [Video]. TED Conferences. URL: [https://www.ted.com/talks/randy_pausch_really_achieving_your_childhood_dreams]([https://www.ted.com/talks/randy_pausch_really_achieving_your_childhood_dreams])
- Warren Robinett. Warren Robinett's Home Page. Accessed October 2023. URL: [http://warrenrobinett.com/](http://warrenrobinett.com/)

::::::::::::::::::::::::::::::::::::: keypoints 

- Virtual Reality Systems have a long history since the early days of computer
graphics.
- The development of headsets have been driven by the game and entertainment industries.
- Researchers envisaged a wide variety of applications, beyond games,
for these systems including tele-operation, communicate different types of 
information/phenomena (e.g. electronic, molecules) to match with our in-built sense,
building the virtual worlds from the inside.

::::::::::::::::::::::::::::::::::::::::::::::::

## More information

[^1]: S. S. Fisher, M. McGreevy, J. Humphries, and W. Robinett. 1987. *Virtual environment display system.* In Proceedings of the 1986 workshop on Interactive 3D graphics (I3D '86). Association for Computing Machinery, New York, NY, USA, 77–87. https://doi.org/10.1145/319120.319127

[^2]: John Barlow, Esther Dyson, Timothy Leary, William Bricken, Warren Robinett, Jaron Lanier, 
and Bob Jacobson. 1990. *Hip, hype and hope—the three faces of virtual worlds (panel session)*. 
In ACM SIGGRAPH 90 Panel Proceedings (SIGGRAPH '90). Association for Computing Machinery, New York, NY, USA, 1001–1029. [https://doi.org/10.1145/328750.328798](https://doi.org/10.1145/328750.328798)
